services:
  py-sample:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
    # ports:
    #   - ${HOST_BINDING:-}${HOST_PORT}:{CONTAINER_PORT}
    # depends_on:
    #   - other_service
    volumes:
      - ./projects:/app/projects
      - ./.vscode:/app/.vscode
    restart: unless-stopped
